- id: turn_sprinklers_on
  alias: "Włacz zraszacze na ruch"
  trigger:
    platform: state
    entity_id: binary_sensor.garden_greenhouse_sensor_motion
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.garden_greenhouse_switch_sprinklers
    
- id: turn_sprinklers_off_after_5
  alias: "Wyłącz zraszacze po 10 min od ruchu"
  trigger:
    platform: state
    entity_id: binary_sensor.garden_greenhouse_sensor_motion
    to: 'off'
    for:
      minutes: '5'
  action:
    service: switch.turn_off
    entity_id: switch.garden_greenhouse_switch_sprinklers
    
- id: toggle_trap
  alias: "Automat rozbrajania"
  trigger:
    platform: state
    entity_id: input_boolean.toggle_garden_greenhouse_trap_automation
  action:
    service_template: >
      {% if is_state('input_boolean.toggle_garden_greenhouse_trap_automation', 'on') %}
        automation.turn_on
      {% else %}
        automation.turn_off     
      {% endif %}
    entity_id: automation.wacz_zraszacze_na_ruch, automation.wyacz_zraszacze_po_10_min_od_ruchu